name: Test

on:
  push:
    branches:
    - master
    - main
    - 'release/**'
  pull_request:

jobs:
  rails_ci:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.3'

    - uses: actions/checkout@v2

    - name: Start MySQL
      run: sudo systemctl start mysql

    - name: Install Node.js
      run: |
        sudo apt update -y
        sudo apt install -y nodejs yarn

    - name: Setup Rails
      env:
        RAILS_ENV: test
        MYSQL_URL: mysql2://root:root@127.0.0.1:3306
      run: bin/setup

    - name: Setup webpack
      env:
        RAILS_ENV: test
      run: |
        yarn
        bin/webpack

    - name: Run RSpec
      env:
        RAILS_ENV: test
        MYSQL_URL: mysql2://root:root@127.0.0.1:3306
      run: bundle exec rspec

    - name: Run RuboCop
      run: bundle exec rubocop
